package com.szreach.ybolotv.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import ybolo.szreach.com.live_vod.bean.LiveList;
import ybolo.szreach.com.live_vod.bean.UserInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig liveListDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final LiveListDao liveListDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        liveListDaoConfig = daoConfigMap.get(LiveListDao.class).clone();
        liveListDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        liveListDao = new LiveListDao(liveListDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(LiveList.class, liveListDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        liveListDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public LiveListDao getLiveListDao() {
        return liveListDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
